// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <head />
//       <body className="bg-white text-black font-sans">
//         <header className="p-4 border-b flex items-center justify-between">
//           <img src="/logo.png" alt="F&R Autosales Logo" className="h-10" />
//           <nav>
//             <a href="/catalog" className="mr-4">Catalog</a>
//             <a href="/appointment" className="mr-4">Appointment</a>
//             <a href="/request">Find My Car</a>
//           </nav>
//         </header>
//         <main className="p-6">{children}</main>
//         <footer className="p-4 border-t text-center text-sm text-gray-500">© 2025 F&R Autosales</footer>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body className="bg-gradient-to-b from-white via-gray-50 to-gray-100 text-black font-sans">
        <header className="p-4 border-b flex items-center justify-between bg-white shadow-md">
          <img src="/logo.png" alt="F&R Autosales Logo" className="h-12" />
          <nav className="space-x-4 text-sm font-semibold">
            <a href="/catalog" className="text-gray-700 hover:text-primary">Catalog</a>
            <a href="/appointment" className="text-gray-700 hover:text-primary">Appointment</a>
            <a href="/request" className="text-gray-700 hover:text-primary">Find My Car</a>
          </nav>
        </header>
        <main className="p-6 max-w-6xl mx-auto">{children}</main>
        <footer className="p-4 border-t text-center text-sm text-gray-600 bg-white">© 2025 F&R Autosales</footer>
      </body>
    </html>
  );
}